name: Test Pull Request Workflow
on: pull_request
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Manoj Test Pull Request Workflow 1"
      - name: Step 2
        run: echo "Test Pull Request Workflow 2"
